language: csharp
solution: netTools.sln
install:
  - nuget restore netTools.sln
  - nuget install NUnit.Console -Version 3.2.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release netTools.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe SolveEquationTests/bin/Release/netcoreapp3.1/SolveEquationTests.dll
