language: csharp
solution: netTools.sln
install:
  - nuget restore netTools.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release netTools.sln
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe SolveEquationTests/bin/Release/netcoreapp3.1/SolveEquationTests.dll
